export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const IS_LOADING = 'IS_LOADING';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const VOTE_SELECTED = 'VOTE_SELECTED';
export const QUESTION_CREATED = 'QUESTION_CREATED';
